pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t vidchap .'
            }
        }
        stage('Test') {
            steps {
                sh 'pytest tests/'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
}
