# sonar.projectKey=vidchap
# sonar.projectName=Vidchap
# sonar.projectVersion=1.0

# # Path to the root of your project
# sonar.projectBaseDir=.

# # Source files (include src folder for React project)
# sonar.sources=src

# # Exclude unnecessary files (node_modules, tests, and build files)
# sonar.exclusions=node_modules/**, build/**, public/**, coverage/**

# # Language settings
# sonar.language=js
# sonar.javascript.lcov.reportPaths=coverage/lcov.info

# # Encoding
# sonar.sourceEncoding=UTF-8

# # Server details (update with your SonarQube server address)
# sonar.host.url=http://localhost:9001
# sonar.login=admin
# sonar.password=vidchap
