sonar.projectKey=vidchap
sonar.projectName=Vidchap
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.language=js
sonar.sources=frontend,backend
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.exclusions=node_modules/**,logs/**,config/**  # Exclude unnecessary files
sonar.password=vidchap
