sonar.projectKey=vidchap-fullstack
sonar.projectName=VidChap Fullstack
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.language=js
sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/build/**,**/logs/**,**/config/**
sonar.test.inclusions=frontend/src/**/*.test.js,frontend/src/**/*.spec.js,backend/tests/**/*.test.js,backend/tests/**/*.spec.js
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.host.url=http://localhost:9000
sonar.login=your_actual_token
