sonar.projectKey=vidchap
sonar.projectName=Vidchap
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.language=js
sonar.sources=frontend/src,backend/src
sonar.host.url=http://sonarqube:9000  # Updated to use the Docker service name (sonarqube)
sonar.login=admin  # SonarQube login (admin by default)
sonar.exclusions=node_modules/**,logs/**,config/**  # Exclude unnecessary files
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
